apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config

data:
  redis.conf: |
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    appendonly yes
    appendfsync everysec
    save 900 1
    save 300 10
    save 60 10000
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir /data
  APP_NAME: redis
  APP_COLOR: red
  