apiVersion: v1
kind: ResourceQuota
metadata:
  name: myapp-quota
  namespace: dev
spec:
  hard:
    requests.cpu: "2"
    pods: "10"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    requests.storage: 10Gi
    limits.storage: 20Gi
    count/pods: "10"
    count/replicationcontrollers: "5"
    count/services: "5"
    count/secrets: "10"
    count/configmaps: "10"