apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp
    type: frontend
spec:
  type: NodePort
  selector:
    app: myapp  # from pod-definition.yaml
    type: frontend  # from pod-definition.yaml 
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008