apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 100000
description: "This priority class should be used for high-priority pods."
globalDefault: false
preemptionPolicy: PreemptLowerPriority
